### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by jdrosales17** [hotwired/hotwire-rails#32]
### Steps to reproduce

Hi,

I was currently debugging a JS error that was happening in IE11 after integrating Hotwire.

When importing `@hotwired/turbo-rails` in our `app/javascript/packs/application.js` we are getting the following error:

```
Function.prototype.toString: 'this' is not a Function object
```

After searching for a while for the solution, I came up with the following tweet:
https://twitter.com/andreas_codered/status/1355452310760120320

So I wanted to confirm that Hotwire effectively won't be supporting IE11...

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 2.6.6

**Comment by mattpolito** [comment]
Since this doesn't look like it has been addressed: 

First, let me state that I in no way speak for this project.  However, being that Microsoft will [no longer support IE 11 on their own flagship apps as of August 2021](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666), I can't imagine maintainers would go out of their way to support it either. That's not to say a PR wouldn't be accepted if it made lives easier for devs and end-users 🤷 

I know it's not an official answer, but I hope that helps.

**Comment by dhh** [comment]
No intend to support IE11 👍

**Comment by jdrosales17** [comment]
Thanks @dhh! 🙌
